version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    volumes:
      - ./html:/usr/share/nginx/html
    tty: true
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    command: ["sh", "-c", "npm install && node index.js"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      retries: 5
      timeout: 10s

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 
      - --init-file
      - /docker-entrypoint-initdb.d/init.sql
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3


networks:
  node-network: 
    driver: bridge